version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.6
        auth:
          username: 6peterlu
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        auth:
          username: 6peterlu
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: peterlu
          POSTGRES_DB: coherencetest
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test