version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.6
        auth:
          username: 6peterlu
          password: $DOCKERHUB_PASSWORD
        environment:
          DATABASE_URL: postgresql://circleci@localhost/coherencetest
          TEST_DATABASE_URI: postgresql://circleci@localhost/coherencetest
          SQLALCHEMY_DATABASE_URI: postgresql://circleci@localhost/coherencetest
          FLASK_ENV: local
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        auth:
          username: 6peterlu
          password: $DOCKERHUB_PASSWORD
        environment:
          PGHOST: localhost
          POSTGRES_USER: circleci
          POSTGRES_DB: coherencetest
          POSTGRES_HOST_AUTH_METHOD: trust
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test