"""empty message

Revision ID: 2431e4335dbf
Revises: 1124335662d2
Create Date: 2021-04-05 13:15:55.440590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2431e4335dbf'
down_revision = '1124335662d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(), nullable=True))
    op.add_column('event', sa.Column('phone_number', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'phone_number')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
