"""remove legacy tables

Revision ID: 411f380c0560
Revises: 5f5121bd8851
Create Date: 2021-04-29 16:45:52.574456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '411f380c0560'
down_revision = '5f5121bd8851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('paused_service')
    op.drop_table('manual_takeover')
    op.drop_table('reminder')
    op.drop_table('concept')
    op.drop_table('dose')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dose',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dose_pkey')
    )
    op.create_table('concept',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time_range_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_range_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='concept_pkey')
    )
    op.create_table('reminder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dose_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('send_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reminder_pkey')
    )
    op.create_table('manual_takeover',
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('phone_number', name='manual_takeover_pkey')
    )
    op.create_table('paused_service',
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('phone_number', name='paused_service_pkey')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='event_pkey')
    )
    # ### end Alembic commands ###
