"""empty message

Revision ID: 412d769b5eef
Revises: 2431e4335dbf
Create Date: 2021-04-11 07:38:02.431995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '412d769b5eef'
down_revision = '2431e4335dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dose', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dose', 'active')
    # ### end Alembic commands ###
