"""add reminders table

Revision ID: 499a3fbafa75
Revises: c14e79845f3a
Create Date: 2021-03-30 13:21:55.998587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '499a3fbafa75'
down_revision = 'c14e79845f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('reminder_type', sa.String(length=10), nullable=False))
    op.alter_column('reminder', 'send_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminder', 'send_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('reminder', 'reminder_type')
    # ### end Alembic commands ###
