"""payment method flag

Revision ID: 4d0317affa3d
Revises: 71158d29ff66
Create Date: 2021-06-02 09:00:27.325422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d0317affa3d'
down_revision = '71158d29ff66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_valid_payment_method', sa.Boolean(), nullable=True))
    op.execute("UPDATE public.user SET has_valid_payment_method = FALSE")  # on migration, everyone gets set to active
    op.alter_column('user', 'has_valid_payment_method', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_valid_payment_method')
    # ### end Alembic commands ###
