"""password hash is a string

Revision ID: 53c7530128bc
Revises: e835238eda36
Create Date: 2021-05-03 21:09:39.539670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53c7530128bc'
down_revision = 'e835238eda36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('dose')
    op.drop_table('reminder')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_table('paused_service')
    op.drop_table('concept')
    op.drop_table('manual_takeover')
    op.alter_column('user', 'password_hash',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.create_table('manual_takeover',
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('phone_number', name='manual_takeover_pkey')
    )
    op.create_table('concept',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time_range_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_range_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='concept_pkey')
    )
    op.create_table('paused_service',
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('phone_number', name='paused_service_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dose_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('send_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reminder_pkey')
    )
    op.create_table('dose',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dose_pkey')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_pkey')
    )
    # ### end Alembic commands ###
