"""remove paused field

Revision ID: 6285c831eb2a
Revises: 6d4e71b117f4
Create Date: 2021-05-15 11:40:40.213827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6285c831eb2a'
down_revision = '6d4e71b117f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'paused')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paused', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
