"""add free trial semantics

Revision ID: 6c4b9422bdb6
Revises: 0a42fd064caa
Create Date: 2021-05-12 11:19:47.693338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c4b9422bdb6'
down_revision = '0a42fd064caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('end_of_service', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('free_trial', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('onboarding', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'onboarding')
    op.drop_column('user', 'free_trial')
    op.drop_column('user', 'end_of_service')
    # ### end Alembic commands ###
