"""state enum

Revision ID: 6d4e71b117f4
Revises: 80e9f193592e
Create Date: 2021-05-14 16:18:04.850895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d4e71b117f4'
down_revision = '80e9f193592e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_state = postgresql.ENUM('intro', 'dose_windows_requested', 'dose_window_times_requested', 'timezone_requested', 'payment_method_requested', 'paused', 'active', 'subscription_expired', name='userstate')
    user_state.create(op.get_bind())
    op.add_column('user', sa.Column('state', user_state, nullable=True))
    op.execute("UPDATE public.user SET state = 'active'")  # on migration, everyone gets set to active
    op.alter_column('user', 'state', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    user_state = postgresql.ENUM('intro', 'dose_windows_requested', 'dose_window_times_requested', 'timezone_requested', 'payment_method_requested', 'paused', 'active', 'subscription_expired', name='userstate')
    user_state.drop(op.get_bind())
    # ### end Alembic commands ###
