"""stripe customer id field

Revision ID: 74e00c05b7d4
Revises: 6285c831eb2a
Create Date: 2021-05-17 07:23:31.766680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74e00c05b7d4'
down_revision = '6285c831eb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
