"""onboarding string flag

Revision ID: 80e9f193592e
Revises: 6c4b9422bdb6
Create Date: 2021-05-12 20:58:02.391755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80e9f193592e'
down_revision = '6c4b9422bdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('onboarding_type', sa.String(), nullable=True))
    op.drop_column('user', 'free_trial')
    op.drop_column('user', 'onboarding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('onboarding', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('free_trial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'onboarding_type')
    # ### end Alembic commands ###
