"""secret code field

Revision ID: bf8eb5022084
Revises: f110d2db868e
Create Date: 2021-05-27 08:20:14.512695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf8eb5022084'
down_revision = 'f110d2db868e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret_text_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'secret_text_code')
    # ### end Alembic commands ###
