"""empty message

Revision ID: c14e79845f3a
Revises: 73386dd87aed
Create Date: 2021-03-30 10:47:51.229990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c14e79845f3a'
down_revision = '73386dd87aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dose', 'phone_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dose', 'phone_number',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
