"""early adopter flag

Revision ID: c932a552b686
Revises: 33fa13ffb88c
Create Date: 2021-05-20 17:01:05.343092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c932a552b686'
down_revision = '33fa13ffb88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('early_adopter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'early_adopter')
    # ### end Alembic commands ###
