"""landing page signup time

Revision ID: f110d2db868e
Revises: 3f7e820c4bcd
Create Date: 2021-05-26 08:55:48.406100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f110d2db868e'
down_revision = '3f7e820c4bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landing_page_signup', sa.Column('signup_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landing_page_signup', 'signup_time')
    # ### end Alembic commands ###
