"""add health metrics column

Revision ID: f11590a9a9a7
Revises: e835238eda36
Create Date: 2021-05-10 19:09:10.320627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f11590a9a9a7'
down_revision = 'e835238eda36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tracked_health_metrics', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tracked_health_metrics')
    # ### end Alembic commands ###
