"""empty message

Revision ID: f1ae6f3a1966
Revises: 
Create Date: 2021-03-30 10:32:19.488901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1ae6f3a1966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_table('follower')
    op.drop_table('writing_session')
    op.drop_table('account')
    op.add_column('dose', sa.Column('medication_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dose', 'medication_name')
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('account_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='account_pkey'),
    sa.UniqueConstraint('email', name='account_email_key'),
    sa.UniqueConstraint('username', name='account_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('writing_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sentence_length_frequency', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('satisfaction', postgresql.ENUM('awful', 'bad', 'good', 'great', 'perfect', name='rating_enum'), autoincrement=False, nullable=True),
    sa.Column('factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('excerpt_end_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('excerpt_start_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fulltext', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('word_frequency', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['account.id'], name='writing_session_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='writing_session_pkey')
    )
    op.create_table('follower',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['account.id'], name='follower_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['account.id'], name='follower_follower_id_fkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
